# Docker version : 1.13.1
# this is build tomcat:8.5, Dockerfile for building jdk images

FROM       idocker.io/eryajf/jdk:1.8

MAINTAINER eryajf <Linuxlql@163.com>

# Install tomcat

ADD  tomcat.tar.gz   /usr/local/

ADD  tomcat.ini /etc/supervisor/conf.d
